export const SET_SUMMARIZED_BY = "SET_SUMMARIZED_BY";
export const SET_GROUP_VARIABLE = "SET_GROUP_VARIABLE";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_EXPANDED_CATEGORIES = "SET_EXPANDED_CATEGORIES";

export const SET_PREVALENCE_FILTER_RANGE = "SET_PREVALENCE_FILTER_RANGE";
export const SET_PREVALENCE_FILTER_SELECTED = "SET_PREVALENCE_FILTER_SELECTED";
export const SET_AGE_FILTER_RANGE = "SET_AGE_FILTER_RANGE";
export const SET_AGE_FILTER_SELECTED = "SET_AGE_FILTER_SELECTED";

export const SET_SERIOUS = "SET_SERIOUS";
export const SET_SEVERITY = "SET_SEVERITY";
export const SET_RELATIONSHIP = "SET_RELATIONSHIP";
export const SET_OUTCOME = "SET_OUTCOME";

export const SET_DETAIL_SEARCH_TERM = "SET_DETAIL_SEARCH_TERM";
export const SET_DETAIL_SORT_COLUMNS = "SET_DETAIL_SORT_COLUMNS";
export const SET_DETAIL_RESULTS_PER_PAGE = "SET_DETAIL_RESULTS_PER_PAGE";
