export const SET_SUMMARIZED_BY = "SET_SUMMARIZED_BY";
export const SET_GROUP_VARIABLE = "SET_GROUP_VARIABLE";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_SORT_COLUMNS = "SET_SORT_COLUMNS";
export const SET_EXPANDED_CATEGORIES = "SET_EXPANDED_CATEGORIES";

export const SET_PREVALENCE_FILTER_RANGE = "SET_PREVALENCE_FILTER_RANGE";
export const SET_PREVALENCE_FILTER_SELECTED = "SET_PREVALENCE_FILTER_SELECTED";
export const SET_PREVALENCE_FILTER_GROUP = "SET_PREVALENCE_FILTER_GROUP";
export const SET_AGE_FILTER_RANGE = "SET_AGE_FILTER_RANGE";
export const SET_AGE_FILTER_SELECTED = "SET_AGE_FILTER_SELECTED";

export const SET_SERIOUS_FILTER = "SET_SERIOUS_FILTER_FILTER";
export const SET_SEVERITY_FILTER = "SET_SEVERITY_FILTER";
export const SET_RELATIONSHIP_FILTER = "SET_RELATIONSHIP_FILTER";
export const SET_OUTCOME_FILTER = "SET_OUTCOME_FILTER";

export const SET_DETAIL_SEARCH_TERM = "SET_DETAIL_SEARCH_TERM";
export const SET_DETAIL_SORT_COLUMNS = "SET_DETAIL_SORT_COLUMNS";
export const SET_DETAIL_RESULTS_PER_PAGE = "SET_DETAIL_RESULTS_PER_PAGE";

export const RESET_STORE = "RESET_STORE";
export const SET_STORE_NAMES = "SET_STORE_NAMES";
