export const SET_SUMMARIZED_BY = "SET_SUMMARIZED_BY";
export const SET_GROUP_VARIABLE = "SET_GROUP_VARIABLE";
export const SET_SERIOUS = "SET_SERIOUS";
export const SET_SEVERITY = "SET_SEVERITY";
export const SET_RELATIONSHIP = "SET_RELATIONSHIP";
export const SET_OUTCOME = "SET_OUTCOME";
